# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /wan-admin
    session:
      timeout: 1800
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    
#自定义参数
wan:
  upload-path: E:\\wan-admin\\upload
  file-folder: File
  image-folder: Image

# Spring配置
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:E:\\wan-admin\\upload


  aop:
    auto: true #启动aop配置
    
  profiles:
    active: database

  # 模板引擎
  freemarker:
    request-context-attribute: request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      classic_compatible: true
    
  # Quartz 的配置，对应 QuartzProperties 配置类
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.wan.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml
  
##日志
logging:
  config: classpath:logback-spring.xml

# https://gitee.com/596392912/mica
mica:
  xss:
    enabled: true
    path-patterns: /**
    path-exclude-patterns: